# Setup
title:        2017 Quito RADseq workshop
tagline:       
baseurl:      
url:          https://rdtarvin.github.io/RADseq_Quito_2017
paginate:     1
theme: jekyll-theme-cayman

# About/contact
author:
 name:       Becca Tarvin
 url:        http://www.rebeccatarvin.com

# Gems
gems:
  - jekyll-paginate
  


#Others
site:
 

